### ISSUE TITLE
No Wifi Hotspot on Start

### ISSUE THREAD

**Issue by debritde** [openhab/openhabian#1954]
After Booting OpenHab on  a Raspberry Pi 3 it says it will start a wifi hotspot which i should connect to to setup my connection to my home wifi.
But there is no wifi hotspot which i can join. It just dont show up on any device

**Comment by debritde** [comment]
Where do i find these logs?
I used RaspiImager to install openhabian 32 bit.
I use a raspberry pi 3.

You can reproduce this by using a pi3 and use the pi imager.

The install log is very useless in this case. The hotspot is not findable anywhere:
```


2024-11-19_13:40:32_UTC [openHABian] Starting the openHABian initial setup.
2024-11-19_13:40:32_UTC [openHABian] Storing configuration... OK
2024-11-19_13:40:32_UTC [openHABian] Starting webserver with installation log... OK
2024-11-19_13:40:37_UTC [openHABian] Changing default username and password... SKIPPED
2024-11-19_13:40:37_UTC [openHABian] Setting up NetworkManager and Wi-Fi connection... 2024-11-19_13:40:40_UTC [openHABian] Ensuring network connectivity... FAILED
2024-11-19_13:40:45_UTC [openHABian] Installing Comitup hotspot... OK
OK
2024-11-19_13:43:07_UTC [openHABian] The public internet is not reachable. Please check your local network environment.
                          We have launched a publicly accessible hotspot named openHABian-<n>.
                          Use a device to connect and go to http://raspberrypi.local or http://10.41.0.1/
                          and select the WiFi network you want to connect your openHABian system to.
                          After about an hour, we will continue trying to get your system installed,
                          but without proper Internet connectivity this is not likely to be going to work.
```

**Comment by mstormi** [comment]
Enable `debuglog=maximum` in `openhabian.conf` BEFORE you boot-to-install. You can mount the first partition from Windows for that.

As I already wrote, the log will be in `/boot/first-boot.log`.

**Comment by debritde** [comment]
[first-boot.log.txt](https://github.com/user-attachments/files/18440279/first-boot.log.txt)

Here is the log.
The SSID i have anonymized is a hidden SSID.
I tried to configure it in the openhabian.conf but this also did not work and the hotspot it should open is not visible anywhere.

**Comment by debritde** [comment]
I configured the wifi in the openhabian.conf.
Since it is hidden the system cannot find it and spins up the hotspot.
I wanna connect to it but doesnt matter if i changed anything in the conf or not, i am never ever able to swee this hotspot if the system says it should show up.

My workaround now is to use a Raspian (Debian) and use openhab over docker.

**Comment by mstormi** [comment]
I don't understand what you mean.
So IS the hotspot up or is it not? (you say it "spins up" ...)

Please log in, sudo to root and tell me what `systemctl status comitup` and `nmcli g` say.
If the latter says wifi is disabled, try `nmcli r wifi on` and once it's up do `systemctl restart comitup` and check if that makes the hotspot WiFi appear

**Comment by mstormi** [comment]
> Since it is hidden the system cannot find it and spins up the hotspot

No. If you give the correct SSID, it should connect there even when it's hidden, so if that didn't work, the reason must be elsewhere.

Can you flash again and edit `firmware/first-boot.bash` before you boot-to-install as follows:
After l99 or so (reading `systemctl enable NetworkManager`), insert these lines:
```
nmcli g
nmcli r wifi on
nmcli g
```

Then try again with your SSID configured in openhabian.conf.

**Comment by mstormi** [comment]
@debritde Can you try again with this image ?
https://github.com/openhab/openhabian/actions/runs/12815570750

**Comment by mstormi** [comment]
I've released v1.9.5 to include this fix. Hotspot works for me.

**Comment by mstormi** [comment]
That's not really a useful comment.
Try [1.12 beta 5](https://github.com/openhab/openhabian/releases/tag/v1.12.0-beta5) please

**Comment by treysis** [comment]
It says that Java 21 is experimental. Shouldn't I better stick with Java 17 and OH4? Also, beta is a beta and 1.11 is current stable?

**Comment by mstormi** [comment]
We don't retro-support fresh installs of outdated OH versions on outpaced hardware so that's up to you.
If I were you, I'd get a new Raspi. But here you're in the wrong place to discuss that, turn to the forum please.

**Comment by treysis** [comment]
No need for more electronic waste. The Rpi3 is just fine handling simple heating control. As far as I understand 1.11 is the current stable. So I just wanted to report the issue is still existant in the latest stable.
